import type { Flavor, Line } from "./domain";

export const lines: Line[] = [
  { id: "burley", name: "BURLEY", number: "01", description: "В основе табачный лист Burley средней или выше средней крепости. По желанию, можно сделать пониже, если поэкспериментировать со способами забивки и миксологией.", accent: "#d84a45" },
  { id: "terror", name: "TERROR", number: "02", description: "В основе табачный лист Burley запредельной крепости, дополнительно прошедший процесс ферментации cavendish. Насыщенная ароматика, стабильная крепость на протяжении всего курения.", accent: "#2a1112" },
  { id: "no-aroma", name: "NO AROMA", number: "03", description: "В основе табачный лист Burley глубокой ферментации на алкогольных варках. Крепкая, насыщенная, дымная. Для каждого раскрывается с разных сторон. Отлично дополняет ароматику!", accent: "#b99a62" },
  { id: "limited", name: "LIMITED", number: "04", description: "Экспериментальные композиции со свободным арт-дирекшном.", accent: "#a42d3b" },
];

export const flavors: Flavor[] = [
  { id: 1, slug: "pera", name: "Pera", displayName: "Pera — Китайская груша", lines: ["burley"], profile: "Фрукты", shortDescription: "Сочная китайская груша с чистым фруктовым звучанием, зелёными травянистыми нотами и естественной свежестью.", fullDescription: "Сочная, свежая, с деликатным вкусом и характерно хрустящей текстурой. Более тонкая и натуральная груша с лёгкими травянисто-зелёными нотами.", notes: ["китайская груша", "зелёные травы", "свежесть"], scores: { sweetness: 3, acidity: 2, freshness: 4, spice: 1, tobacco: 2 }, archetype: "Fruit" },
  { id: 2, slug: "cantalupo", name: "Cantalupo", displayName: "Cantalupo — Мускусная дыня", lines: ["burley"], profile: "Фрукты · тропический", shortDescription: "Спелая мускусная дыня: бархатистая сладость, тёплый тропический характер и тонкая пряность.", fullDescription: "Объёмный вкус спелой дыни с бархатистой мякотью, тёплым мускусом и тонкими тропическими оттенками — натурально и ярко, без леденцовости.", notes: ["мускусная дыня", "тропические ноты", "тёплый мускус", "лёгкая пряность"], scores: { sweetness: 5, acidity: 1, freshness: 2, spice: 2, tobacco: 2 }, archetype: "Fruit Tropical" },
  { id: 3, slug: "taste", name: "Taste", displayName: "Вкус (Taste)", lines: ["limited"], profile: "Напиточный · тропический", shortDescription: "Фестивальный твист на «Фернандиту»: живая коктейльная композиция на базе Burley.", fullDescription: "Многогранная фестивальная композиция, созданная как вкус-воспоминание о JC2026 и вдохновлённая коктейлем «Фернандита».", notes: ["коктейльный профиль", "тропический характер", "фестивальная композиция"], scores: { sweetness: 3, acidity: 3, freshness: 3, spice: 2, tobacco: 2 }, archetype: "Drink / Limited" },
  { id: 4, slug: "truth", name: "Truth", displayName: "Правда (Truth)", lines: ["limited"], profile: "Неароматика", shortDescription: "Честная, насыщенная неароматика на плотном Burley: объём и крепость без прикрас.", fullDescription: "Увесистый Burley, приготовленный так, чтобы сохранить первобытность табачного вкуса, его объём и насыщенность.", notes: ["Burley", "плотный табачный вкус", "насыщенность"], scores: { sweetness: 1, acidity: 1, freshness: 1, spice: 3, tobacco: 5 }, archetype: "Tobacco Raw" },
  { id: 5, slug: "goodness", name: "Goodness", displayName: "Добро (Goodness)", lines: ["limited"], profile: "Неароматика", shortDescription: "Сбалансированная неароматика на итальянском Burley, вываренном на хересе Ореанда.", fullDescription: "Глубокий и спокойный профиль итальянского Burley с благородной выдержкой и многогранным хересным характером.", notes: ["итальянский Burley", "херес Ореанда", "выдержка", "глубина"], scores: { sweetness: 2, acidity: 1, freshness: 1, spice: 3, tobacco: 5 }, archetype: "Tobacco Alcohol" },
  { id: 6, slug: "beauty", name: "Beauty", displayName: "Красота (Beauty)", lines: ["limited"], profile: "Неароматика", shortDescription: "Красный виноград, сухофрукты, медовуха, специи и шоколад поверх итальянского Burley.", fullDescription: "Многослойная композиция: красный виноград и сухофрукты переходят в медовуху, специи и шоколад на основе классического Burley.", notes: ["красный виноград", "сухофрукты", "медовуха", "специи", "шоколад"], scores: { sweetness: 4, acidity: 2, freshness: 1, spice: 4, tobacco: 5 }, archetype: "Tobacco Complex" },
  { id: 7, slug: "limoncello", name: "Limoncello", displayName: "Limoncello", lines: ["no-aroma"], profile: "Цитрусовый · алкогольный", shortDescription: "Burley, отферментированный на Limoncello: сладкий лимон, тонкая горчинка и цитрусовая свежесть.", fullDescription: "Табачный лист Burley раскрывается сладким лимоном, тонкой горчинкой и интенсивной свежестью итальянского ликёра.", notes: ["лимон", "Limoncello", "горчинка", "цитрусовая свежесть"], scores: { sweetness: 4, acidity: 4, freshness: 5, spice: 1, tobacco: 4 }, archetype: "Citrus Alcohol" },
  { id: 8, slug: "wild-strawberry", name: "Wild Strawberry", displayName: "Wild Strawberry", lines: ["burley", "terror"], profile: "Ягоды", shortDescription: "Свежесозревшая дикая земляника с ярким кисло-сладким характером.", fullDescription: "Кисло-сладкая дикая ягода, которая только что созрела.", notes: ["дикая земляника", "сладость", "кислинка"], scores: { sweetness: 4, acidity: 4, freshness: 3, spice: 1, tobacco: 2 }, archetype: "Berry" },
  { id: 9, slug: "abricot", name: "Abricot", displayName: "Abricot", lines: ["burley", "terror"], profile: "Фрукты · пряный", shortDescription: "Натуральный абрикос с кислинкой, корицей и характерной нотой косточки.", fullDescription: "Не абрикосовое варенье, а натуральный фрукт с отчётливой кислинкой, корицей и сухой нотой абрикосовой косточки.", notes: ["абрикос", "кислинка", "корица", "абрикосовая косточка"], scores: { sweetness: 3, acidity: 4, freshness: 2, spice: 4, tobacco: 2 }, archetype: "Fruit Spice" },
  { id: 10, slug: "jenever", name: "Jenever", displayName: "Jenever", lines: ["no-aroma"], profile: "Ботанический · алкогольный", shortDescription: "Burley на Jenever: можжевельник, ирис, миндаль, кориандр и дудник.", fullDescription: "Пряный цветочно-ягодный профиль голландского Jenever соединяется с хлопьями табачного листа Burley.", notes: ["можжевельник", "корень ириса", "миндаль", "кориандр", "дудник"], scores: { sweetness: 2, acidity: 2, freshness: 3, spice: 5, tobacco: 4 }, archetype: "Botanical Alcohol" },
  { id: 11, slug: "kriek", name: "Kriek", displayName: "Kriek", lines: ["burley", "terror"], profile: "Ягоды", shortDescription: "Спелая черешня и тёмная вишня с терпким ягодным соком и кислинкой.", fullDescription: "Сочетание спелой черешни и тёмной вишни раскрывается как терпкий вишнёвый сок в духе бельгийского Kriek.", notes: ["черешня", "тёмная вишня", "терпкий сок", "кислинка"], scores: { sweetness: 4, acidity: 4, freshness: 2, spice: 1, tobacco: 2 }, archetype: "Berry Dark" },
  { id: 12, slug: "virgin", name: "Virgin", displayName: "Virgin", lines: ["no-aroma"], profile: "Табачный", shortDescription: "Чистая итальянская Virginia: мягкая, стабильная и карамельная неароматика.", fullDescription: "Моносорт Virginia без дополнительных примесей — мягкий и приветливый профиль, задуманный как бустер лёгкости.", notes: ["Virginia", "карамельность", "мягкость", "лёгкость"], scores: { sweetness: 3, acidity: 1, freshness: 1, spice: 2, tobacco: 5 }, archetype: "Tobacco Origin" },
  { id: 13, slug: "anejo", name: "Anejo", displayName: "Anejo", lines: ["no-aroma"], profile: "Табачный · алкогольный", shortDescription: "Купаж Virginia и Burley с ромом: сладкая пряность, фруктовая кислинка и древесное ядро.", fullDescription: "Сбалансированный купаж итальянских Virginia и Burley с ромом, мягче самых крепких историй бренда.", notes: ["Virginia", "Burley", "ром", "сладкая пряность", "древесность"], scores: { sweetness: 3, acidity: 2, freshness: 1, spice: 4, tobacco: 5 }, archetype: "Tobacco Blend Alcohol" },
  { id: 14, slug: "ruby-grapes", name: "Ruby Grapes", displayName: "Ruby Grapes", lines: ["burley"], profile: "Фрукты · ягоды", shortDescription: "Сочный кишмиш: сладость, яркая кислинка и лёгкая виноградная терпкость.", fullDescription: "Яркий вкус винограда кишмиш со сладостью, отчётливой кислинкой, сочностью и ненавязчивой терпкостью.", notes: ["кишмиш", "сладость", "кислинка", "терпкость"], scores: { sweetness: 4, acidity: 4, freshness: 3, spice: 1, tobacco: 2 }, archetype: "Fruit Grapes" },
  { id: 15, slug: "cookies", name: "Cookies", displayName: "Cookies", lines: ["burley"], profile: "Десертный", shortDescription: "Яркое шоколадное печенье с лёгкой кокосовой ноткой.", fullDescription: "Насыщенное шоколадное печенье с тонкой кокосовой нотой — выразительное соло и основа для десертных миксов.", notes: ["шоколадное печенье", "кокос"], scores: { sweetness: 5, acidity: 1, freshness: 1, spice: 2, tobacco: 2 }, archetype: "Dessert" },
];

export const getFlavor = (slug: string) => flavors.find((flavor) => flavor.slug === slug);
